-- SnapHere standalone schema
-- Target: Percona Distribution for PostgreSQL 17.10.2 + PostGIS 3.6.2 (custom image)
-- Source: supplied data-design v1.1.3 (28 tables)
--
-- Run this file in an EMPTY database. This file is intentionally outside
-- db/migration and is not applied by the application's Flyway configuration.
-- Database roles, passwords, and CREATE DATABASE are intentionally excluded.

begin;

set local timezone = 'UTC';

create extension if not exists postgis;
create extension if not exists pg_trgm;

-- ---------------------------------------------------------------------------
-- Enum types
-- ---------------------------------------------------------------------------

create type provider as enum ('GOOGLE');
create type user_role as enum ('USER', 'ADMIN');
create type user_status as enum ('ACTIVE', 'SUSPENDED', 'WITHDRAWN');
create type content_action as enum ('KEEP_ANONYMIZED', 'DELETE_ALL');
create type device_platform as enum ('ANDROID', 'IOS');
create type place_type as enum ('OFFICIAL', 'USER');
create type post_tier as enum ('HIGH', 'MEDIUM', 'LOW');
create type post_source as enum ('CAMERA', 'ALBUM');
create type post_status as enum ('ACTIVE', 'BLINDED', 'DELETED');
create type comment_status as enum ('ACTIVE', 'DELETED');
create type like_target as enum ('POST', 'COMMENT');
create type bookmark_target as enum ('POST', 'PLACE');
create type badge_type as enum ('EVENT', 'AREA', 'COMPLETION', 'RECORD');
create type event_source as enum ('TOURAPI', 'MANUAL');
create type heatmap_period as enum ('LAST_1H', 'LAST_24H', 'WEEKLY', 'MONTHLY');
create type post_popularity_period as enum ('HOURS_24', 'WEEKLY', 'MONTHLY', 'ALL');
create type ranking_period as enum ('DAILY', 'WEEKLY', 'MONTHLY', 'ALL');
create type notification_type as enum ('POST_LIKE', 'FOLLOW', 'BADGE_EARNED', 'SYSTEM');
create type notification_target as enum ('POST', 'USER', 'BADGE', 'NONE');
create type report_target as enum ('POST', 'COMMENT', 'PLACE', 'USER');
create type report_status as enum ('PENDING', 'RESOLVED', 'REJECTED');
create type sync_result as enum ('SUCCESS', 'FAIL', 'PARTIAL');

-- ---------------------------------------------------------------------------
-- Accounts
-- ---------------------------------------------------------------------------

create table users (
    user_id              bigint generated by default as identity primary key,
    provider             provider not null default 'GOOGLE',
    provider_user_id     varchar(255),
    email                varchar(255),
    nickname             varchar(20) not null,
    profile_image_url    varchar(500),
    bio                  varchar(200),
    locale               varchar(10) not null default 'ko',
    role                 user_role not null default 'USER',
    status               user_status not null default 'ACTIVE',
    upload_blocked_until timestamptz,
    push_like_enabled    boolean not null default true,
    push_follow_enabled  boolean not null default true,
    push_badge_enabled   boolean not null default true,
    badge_count          integer not null default 0,
    follower_count       integer not null default 0,
    following_count      integer not null default 0,
    post_count           integer not null default 0,
    withdrawn_at         timestamptz,
    purge_scheduled_at   timestamptz,
    restore_key          char(64),
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now(),
    constraint ck_users_nickname_length check (char_length(nickname) between 2 and 20),
    constraint ck_users_locale check (locale in ('ko', 'en', 'zh', 'ja')),
    constraint ck_users_counts check (
        badge_count >= 0 and follower_count >= 0 and following_count >= 0 and post_count >= 0
    ),
    constraint ck_users_withdrawal check (
        status <> 'WITHDRAWN' or withdrawn_at is not null
    )
);

create unique index uk_users_provider on users (provider, provider_user_id);
create index idx_users_nickname on users (nickname);
create index idx_users_purge on users (purge_scheduled_at)
    where purge_scheduled_at is not null;

comment on table users is 'Google OAuth account. role is authorization, not membership grade.';
comment on column users.restore_key is 'SHA-256 hash used only to match an account restoration request.';

create table user_devices (
    device_id   bigint generated by default as identity primary key,
    user_id     bigint not null references users(user_id),
    fcm_token   varchar(255),
    platform    device_platform not null,
    app_version varchar(20),
    updated_at  timestamptz not null default now()
);

create unique index uk_devices_token on user_devices (user_id, fcm_token);

create table refresh_tokens (
    token_hash char(64) primary key,
    user_id    bigint not null references users(user_id),
    device_id  bigint references user_devices(device_id),
    expires_at timestamptz not null,
    revoked_at timestamptz,
    constraint ck_refresh_token_expiry check (expires_at > coalesce(revoked_at, '-infinity'::timestamptz))
);

create index idx_refresh_user on refresh_tokens (user_id);

create table account_deletion_logs (
    log_id         bigint generated by default as identity primary key,
    user_id        bigint not null references users(user_id),
    reason         varchar(500),
    content_action content_action not null,
    deleted_at     timestamptz not null,
    purged_at      timestamptz,
    constraint ck_account_deletion_order check (purged_at is null or purged_at >= deleted_at)
);

-- ---------------------------------------------------------------------------
-- Social
-- ---------------------------------------------------------------------------

create table follows (
    follower_id  bigint not null references users(user_id),
    following_id bigint not null references users(user_id),
    created_at   timestamptz not null default now(),
    primary key (follower_id, following_id),
    constraint ck_follows_not_self check (follower_id <> following_id)
);

create index idx_follows_following on follows (following_id);

-- ---------------------------------------------------------------------------
-- Places
-- ---------------------------------------------------------------------------

create table regions (
    area_code                     integer primary key,
    name_ko                       varchar(50) not null,
    name_en                       varchar(50) not null,
    representative_image_url      varchar(500),
    default_event_verify_radius_m integer not null default 2000,
    constraint ck_regions_radius check (default_event_verify_radius_m > 0)
);

create table sigungu (
    area_code    integer not null references regions(area_code),
    sigungu_code integer not null,
    name_ko      varchar(50) not null,
    name_en      varchar(50),
    primary key (area_code, sigungu_code)
);

create table places (
    place_id        bigint generated by default as identity primary key,
    place_type      place_type not null,
    content_id      bigint unique,
    content_type_id integer,
    title           varchar(200) not null,
    addr1           varchar(300),
    geom            geography(Point, 4326),
    verify_radius_m integer not null,
    area_code       integer not null references regions(area_code),
    sigungu_code    integer,
    has_coordinate  boolean not null default true,
    post_count      integer not null default 0,
    visit_count     integer not null default 0,
    view_count      integer not null default 0,
    created_by      bigint references users(user_id),
    created_at      timestamptz not null default now(),
    constraint fk_places_sigungu foreign key (area_code, sigungu_code)
        references sigungu(area_code, sigungu_code),
    constraint ck_places_radius check (verify_radius_m > 0),
    constraint ck_places_coordinate_flag check (has_coordinate = (geom is not null)),
    constraint ck_places_counts check (post_count >= 0 and visit_count >= 0 and view_count >= 0),
    constraint ck_places_owner check (
        (place_type = 'OFFICIAL' and created_by is null)
        or (place_type = 'USER' and created_by is not null)
    )
);

create index gix_places_geom on places using gist (geom);
create index idx_places_area_type on places (area_code, place_type);
create index gin_places_title on places using gin (
    title gin_trgm_ops,
    addr1 gin_trgm_ops
);

comment on column places.geom is 'TourAPI mapx=longitude, mapy=latitude. Build with ST_MakePoint(lng, lat)::geography.';

create table place_details (
    place_id      bigint not null references places(place_id),
    language_code varchar(10) not null default 'ko',
    overview      text,
    tel           varchar(50),
    homepage      varchar(500),
    use_time      varchar(500),
    rest_date     varchar(200),
    primary key (place_id, language_code),
    constraint ck_place_details_language check (language_code in ('ko', 'en', 'zh', 'ja'))
);

-- Events are created before posts because posts.event_id references this table.
create table events (
    event_id          bigint generated by default as identity primary key,
    content_id        bigint unique,
    title             varchar(200) not null,
    overview          text,
    area_code         integer not null references regions(area_code),
    place_id          bigint references places(place_id),
    start_date        date not null,
    end_date          date not null,
    thumbnail_url     varchar(500),
    fixed_tags        jsonb,
    participant_count integer not null default 0,
    source            event_source not null,
    verify_radius_m   integer,
    constraint ck_events_period check (end_date >= start_date),
    constraint ck_events_participants check (participant_count >= 0),
    constraint ck_events_radius check (verify_radius_m is null or verify_radius_m > 0),
    constraint ck_events_fixed_tags check (fixed_tags is null or jsonb_typeof(fixed_tags) = 'array')
);

create index idx_events_area_period on events (area_code, start_date, end_date);
create index idx_events_period on events (start_date, end_date);

-- ---------------------------------------------------------------------------
-- Posts
-- ---------------------------------------------------------------------------

create table posts (
    post_id                bigint generated by default as identity primary key,
    user_id                bigint not null references users(user_id),
    place_id               bigint not null references places(place_id),
    event_id               bigint references events(event_id),
    content                text,
    original_language_code varchar(10),
    tier                   post_tier not null,
    lat                    numeric(10, 7),
    lng                    numeric(10, 7),
    taken_at               timestamptz,
    source                 post_source not null,
    area_code              integer not null references regions(area_code),
    like_count             integer not null default 0,
    comment_count          integer not null default 0,
    view_count             integer not null default 0,
    status                 post_status not null default 'ACTIVE',
    created_at             timestamptz not null default now(),
    updated_at             timestamptz not null default now(),
    deleted_at             timestamptz,
    constraint ck_posts_content_length check (content is null or char_length(content) <= 5000),
    constraint ck_posts_lat check (lat is null or lat between -90 and 90),
    constraint ck_posts_lng check (lng is null or lng between -180 and 180),
    constraint ck_posts_coordinates check ((lat is null) = (lng is null)),
    constraint ck_posts_counts check (like_count >= 0 and comment_count >= 0 and view_count >= 0),
    constraint ck_posts_deleted_at check (status <> 'DELETED' or deleted_at is not null)
);

create index idx_posts_area_created on posts (area_code, created_at desc)
    where status = 'ACTIVE';
create index idx_posts_place on posts (place_id, created_at desc)
    where status = 'ACTIVE';
create index idx_posts_user on posts (user_id, created_at desc)
    where status = 'ACTIVE';
create index idx_posts_event on posts (event_id);
create index idx_posts_ranking on posts (status, tier, created_at desc);

create table post_images (
    post_image_id bigint generated by default as identity primary key,
    post_id       bigint not null references posts(post_id),
    image_key     varchar(500) not null,
    thumbnail_url varchar(500),
    aspect_ratio  numeric(5, 3),
    sort_order    smallint not null,
    constraint uk_post_images_order unique (post_id, sort_order),
    constraint ck_post_images_aspect check (aspect_ratio is null or aspect_ratio > 0),
    constraint ck_post_images_order check (sort_order between 0 and 3)
);

-- ---------------------------------------------------------------------------
-- Community
-- ---------------------------------------------------------------------------

create table comments (
    comment_id bigint generated by default as identity primary key,
    post_id    bigint not null references posts(post_id),
    user_id    bigint not null references users(user_id),
    parent_id  bigint references comments(comment_id),
    content    varchar(1000) not null,
    like_count integer not null default 0,
    status     comment_status not null default 'ACTIVE',
    created_at timestamptz not null default now(),
    constraint ck_comments_content check (char_length(content) between 1 and 1000),
    constraint ck_comments_likes check (like_count >= 0),
    constraint ck_comments_not_self_parent check (parent_id is null or parent_id <> comment_id)
);

create index idx_comments_post on comments (post_id, created_at)
    where status = 'ACTIVE';
create index idx_comments_parent on comments (parent_id);

create table likes (
    user_id     bigint not null references users(user_id),
    target_type like_target not null,
    target_id   bigint not null,
    created_at  timestamptz not null default now(),
    primary key (user_id, target_type, target_id)
);

create index idx_likes_target on likes (target_type, target_id);

create table bookmarks (
    user_id     bigint not null references users(user_id),
    target_type bookmark_target not null,
    target_id   bigint not null,
    created_at  timestamptz not null default now(),
    primary key (user_id, target_type, target_id)
);

create table tags (
    tag_id          bigint generated by default as identity primary key,
    name            varchar(50) not null,
    normalized_name varchar(50) not null unique,
    theme_code      varchar(30),
    usage_count     integer not null default 0,
    constraint ck_tags_usage check (usage_count >= 0)
);

create table post_tags (
    post_id      bigint not null references posts(post_id),
    tag_id       bigint not null references tags(tag_id),
    is_locked    boolean not null default false,
    is_suggested boolean not null default false,
    primary key (post_id, tag_id)
);

create index idx_post_tags_tag on post_tags (tag_id);

-- ---------------------------------------------------------------------------
-- Badges
-- ---------------------------------------------------------------------------

create table badges (
    badge_id       bigint generated by default as identity primary key,
    code           varchar(50) not null unique,
    type           badge_type not null,
    name_ko        varchar(50) not null,
    name_en        varchar(50) not null,
    description    varchar(300),
    icon_url       varchar(500),
    condition_json jsonb not null,
    event_id       bigint unique references events(event_id),
    area_code      integer references regions(area_code),
    is_obtainable  boolean not null default true,
    available_from timestamptz,
    available_to   timestamptz,
    constraint ck_badges_condition check (
        jsonb_typeof(condition_json) = 'object' and condition_json ? 'type'
    ),
    constraint ck_badges_availability check (
        available_to is null or available_from is null or available_to >= available_from
    ),
    constraint ck_badges_target check (
        (type = 'EVENT' and event_id is not null and area_code is null)
        or (type = 'AREA' and area_code is not null and event_id is null)
        or (type in ('COMPLETION', 'RECORD') and event_id is null and area_code is null)
    )
);

create table user_badges (
    user_id        bigint not null references users(user_id),
    badge_id       bigint not null references badges(badge_id),
    earned_at      timestamptz not null default now(),
    source_post_id bigint references posts(post_id) on delete set null,
    primary key (user_id, badge_id)
);

-- ---------------------------------------------------------------------------
-- Visits and aggregate snapshots
-- ---------------------------------------------------------------------------

create table visits (
    visit_id   bigint generated by default as identity primary key,
    user_id    bigint not null references users(user_id),
    place_id   bigint not null references places(place_id),
    post_id    bigint references posts(post_id) on delete set null,
    visited_on date not null,
    constraint uk_visits_daily unique (user_id, place_id, visited_on)
);

create index idx_visits_user on visits (user_id, visited_on desc);

create table heatmap_cells (
    cell_id         bigint generated by default as identity primary key,
    grid_level      smallint not null,
    lat             numeric(10, 7) not null,
    lng             numeric(10, 7) not null,
    period          heatmap_period not null,
    post_count      integer not null default 0,
    visit_count     integer not null default 0,
    user_count      integer not null default 0,
    top_place_id    bigint references places(place_id),
    sample_post_ids jsonb,
    last_posted_at  timestamptz,
    calculated_at   timestamptz not null default now(),
    constraint uk_heatmap_cell unique (grid_level, period, lat, lng),
    constraint ck_heatmap_level check (grid_level between 0 and 3),
    constraint ck_heatmap_lat check (lat between -90 and 90),
    constraint ck_heatmap_lng check (lng between -180 and 180),
    constraint ck_heatmap_counts check (post_count >= 0 and visit_count >= 0 and user_count >= 0),
    constraint ck_heatmap_samples check (
        sample_post_ids is null
        or (jsonb_typeof(sample_post_ids) = 'array' and jsonb_array_length(sample_post_ids) <= 10)
    )
);

create table post_rankings (
    post_id       bigint not null references posts(post_id),
    period        post_popularity_period not null,
    score         numeric(12, 4) not null,
    rank_no       integer not null,
    calculated_at timestamptz not null default now(),
    primary key (post_id, period),
    constraint ck_post_rankings_score check (score >= 0),
    constraint ck_post_rankings_rank check (rank_no > 0)
);

create index idx_post_rankings_lookup on post_rankings (period, rank_no);

create table region_stats (
    area_code        integer not null references regions(area_code),
    period           heatmap_period not null,
    post_count       integer not null default 0,
    contributor_count integer not null default 0,
    primary key (area_code, period),
    constraint ck_region_stats_counts check (post_count >= 0 and contributor_count >= 0)
);

create table place_rankings (
    ranking_id    bigint generated by default as identity primary key,
    place_id      bigint not null references places(place_id),
    area_code     integer not null references regions(area_code),
    period        ranking_period not null,
    theme         varchar(30) not null default 'ALL',
    score         numeric(12, 4) not null,
    rank_no       integer not null,
    previous_rank integer,
    calculated_at timestamptz not null default now(),
    constraint uk_rankings_key unique (place_id, period, theme),
    constraint ck_place_rankings_score check (score >= 0),
    constraint ck_place_rankings_rank check (rank_no > 0),
    constraint ck_place_rankings_previous check (previous_rank is null or previous_rank > 0)
);

create index idx_rankings_lookup on place_rankings (area_code, period, theme, rank_no);

-- ---------------------------------------------------------------------------
-- Notifications and operations
-- ---------------------------------------------------------------------------

create table notifications (
    notification_id bigint generated by default as identity primary key,
    recipient_id    bigint not null references users(user_id),
    actor_id        bigint references users(user_id),
    type            notification_type not null,
    target_type     notification_target not null,
    target_id       bigint,
    message_key     varchar(100) not null,
    message_params  jsonb,
    is_read         boolean not null default false,
    created_at      timestamptz not null default now(),
    constraint uk_notifications_dedup unique (
        recipient_id, actor_id, type, target_type, target_id
    ),
    constraint ck_notifications_target check (
        (target_type = 'NONE' and target_id is null)
        or (target_type <> 'NONE' and target_id is not null)
    ),
    constraint ck_notifications_params check (
        message_params is null or jsonb_typeof(message_params) = 'object'
    )
);

create index idx_notifications_unread on notifications (recipient_id, is_read)
    where is_read = false;

create table reports (
    report_id   bigint generated by default as identity primary key,
    reporter_id bigint not null references users(user_id),
    target_type report_target not null,
    target_id   bigint not null,
    reason      varchar(300) not null,
    status      report_status not null default 'PENDING',
    created_at  timestamptz not null default now(),
    constraint uk_reports_dedup unique (reporter_id, target_type, target_id)
);

create index idx_reports_target on reports (target_type, target_id);

create table sync_logs (
    sync_id         bigint generated by default as identity primary key,
    job_type        varchar(50) not null,
    area_code       integer references regions(area_code),
    content_type_id integer,
    result          sync_result not null,
    count           integer not null default 0,
    message         varchar(500),
    created_at      timestamptz not null default now(),
    constraint ck_sync_logs_count check (count >= 0),
    constraint ck_sync_logs_job_type check (
        job_type in ('PLACE', 'EVENT', 'RANKING', 'HEATMAP', 'COUNTER_FIX')
    )
);

create table search_logs (
    log_id      bigint generated by default as identity primary key,
    keyword     varchar(100) not null,
    area_code   integer references regions(area_code),
    searched_at timestamptz not null default now()
);

create index idx_search_keyword on search_logs (keyword, searched_at desc);

commit;
