-- SnapHere V10 — 댓글
-- 요구사항: CMU-012, CMU-013, CMU-014, CMU-015, CMU-017, CMU-018
-- 설계: 요구사항·기능 명세 v1.1.4 > 6. 데이터 설계 > comments
--
-- 대댓글은 한 단계까지만 둔다 (CMU-015). parent_id 는 항상 최상위 댓글을 가리키고,
-- 대댓글에 다시 답글을 달면 서비스가 부모를 최상위로 올려 같은 스레드에 붙인다.
-- "부모의 parent_id 가 null 이어야 한다"는 조건은 다른 행을 봐야 하므로 CHECK 로 쓸 수 없고,
-- 트리거로 막으면 규칙이 코드와 DB 두 곳에 흩어진다. 그래서 깊이는 CommentService 가 지킨다.

create table comments (
    comment_id bigint       generated by default as identity primary key,
    post_id    bigint       not null,
    user_id    uuid         not null,
    parent_id  bigint,
    content    varchar(1000),
    like_count integer      not null default 0,
    status     varchar(20)  not null default 'ACTIVE',
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now(),

    constraint ck_comments_status check (status in ('ACTIVE', 'DELETED')),
    constraint ck_comments_like_count check (like_count >= 0),
    -- 살아 있는 댓글은 본문이 있어야 하고, 삭제된 댓글은 본문을 지운다 (CMU-017).
    constraint ck_comments_content check ((status = 'ACTIVE' and content is not null and length(content) between 1 and 1000)
                                       or (status = 'DELETED' and content is null)),
    constraint ck_comments_not_self check (parent_id is null or parent_id <> comment_id),
    constraint fk_comments_post foreign key (post_id) references posts (post_id) on delete cascade,
    constraint fk_comments_user foreign key (user_id) references users (id) on delete cascade,
    constraint fk_comments_parent foreign key (parent_id) references comments (comment_id) on delete cascade
);

comment on table comments is
'댓글. 대댓글 깊이는 한 단계다 — parent_id 는 항상 최상위 댓글을 가리킨다 (CMU-015)';
comment on column comments.parent_id is
'최상위 댓글 ID. null 이면 이 행이 최상위 댓글이다';
comment on column comments.content is
'삭제하면 null 로 비운다. 자식이 있는 댓글은 행을 남겨 자리표시자로 쓴다 (CMU-017)';
comment on column comments.like_count is
'댓글 좋아요 수 (CMU-018). likes 를 매번 세지 않기 위한 집계 컬럼이다';

-- 최상위 댓글 목록은 최신순 커서 페이징이다 (CMU-013, CMU-010).
-- parent_id is null 부분 인덱스로 대댓글 행을 인덱스에서 빼 스레드 목록 조회를 가볍게 한다.
create index idx_comments_post_root on comments (post_id, created_at desc, comment_id desc)
    where parent_id is null;

-- 자식은 부모 목록을 받아 IN 절로 한 번에 모아 온다 — 부모마다 조회하면 N+1 이다 (CMU-013).
create index idx_comments_parent on comments (parent_id, created_at, comment_id)
    where parent_id is not null;
