-- SnapHere V11 — PLC-001~PLC-023 장소 조회·운영 확장
-- V1~V10의 공용 Auth/JPA/게시글·반응·신고·댓글 스키마를 유지하면서 장소 기능에 필요한 필드와 테이블만 추가한다.

alter table places add column normalized_title varchar(200);
alter table places add column image_url varchar(2048);
alter table places add column source_modified_at timestamptz;

update places
set normalized_title = lower(regexp_replace(trim(title), '\s+', ' ', 'g'))
where normalized_title is null;

alter table places alter column normalized_title set not null;
create index gin_places_normalized_title on places using gin (normalized_title gin_trgm_ops);
create index idx_places_creator_day on places (created_by, created_at) where place_type = 'USER';

create table place_details (
    place_id      bigint        not null references places(place_id) on delete cascade,
    language_code varchar(10)   not null,
    overview      text,
    tel           varchar(100),
    homepage      text,
    use_time      text,
    rest_date     text,
    loaded_at     timestamptz   not null default now(),
    primary key (place_id, language_code)
);

create table events (
    event_id        bigint generated by default as identity primary key,
    content_id      varchar(100) unique,
    title           varchar(200) not null,
    overview        text,
    area_code       integer not null references regions(area_code),
    place_id        bigint not null references places(place_id),
    start_date      date not null,
    end_date        date not null,
    thumbnail_url   varchar(2048),
    fixed_tags      jsonb not null default '[]'::jsonb,
    participant_count integer not null default 0,
    source          varchar(20) not null default 'MANUAL',
    verify_radius_m integer,
    status          varchar(20) not null default 'ACTIVE',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint ck_events_date check (end_date >= start_date),
    constraint ck_events_radius check (verify_radius_m is null or verify_radius_m between 1 and 20000)
);

alter table posts add constraint fk_posts_event foreign key (event_id) references events(event_id);

create table place_rankings (
    ranking_id     bigint generated by default as identity primary key,
    place_id       bigint not null references places(place_id) on delete cascade,
    area_code      integer not null references regions(area_code),
    period         varchar(20) not null,
    theme          varchar(100) not null default 'ALL',
    score          numeric(18,4) not null default 0,
    rank_no        integer not null,
    previous_rank  integer,
    calculated_at  timestamptz not null default now(),
    unique (place_id, period, theme)
);

create table batch_runs (
    run_id          bigint generated by default as identity primary key,
    job_type        varchar(50) not null,
    status          varchar(20) not null,
    processed_count integer not null default 0,
    failed_count    integer not null default 0,
    started_at      timestamptz,
    finished_at     timestamptz,
    created_at      timestamptz not null default now(),
    constraint ck_batch_runs_status check (status in ('QUEUED', 'RUNNING', 'SUCCESS', 'FAIL'))
);

create unique index uk_running_batch_job on batch_runs(job_type)
where status in ('QUEUED', 'RUNNING');

create table sync_logs (
    sync_id         bigint generated by default as identity primary key,
    run_id          bigint not null references batch_runs(run_id) on delete cascade,
    job_type        varchar(50) not null,
    area_code       integer references regions(area_code),
    content_type_id integer,
    result          varchar(20) not null,
    count           integer not null default 0,
    message         text,
    started_at      timestamptz not null default now(),
    finished_at     timestamptz,
    constraint ck_sync_logs_result check (result in ('SUCCESS', 'FAIL', 'PARTIAL'))
);

create index idx_sync_logs_cursor on sync_logs(sync_id desc);
