-- SnapHere V12 — MAP-001~MAP-030 지도 사전 집계

create table heatmap_cells (
    cell_id                bigint generated by default as identity primary key,
    period                 varchar(20) not null,
    grid_level             smallint not null,
    lat_index              integer not null,
    lng_index              integer not null,
    lat                    double precision not null,
    lng                    double precision not null,
    post_count             integer not null,
    visit_count            integer not null default 0,
    user_count             integer not null,
    top_place_id           bigint references places(place_id) on delete set null,
    sample_post_ids        bigint[] not null default '{}',
    sample_thumbnail_urls  text[] not null default '{}',
    last_posted_at         timestamptz,
    calculated_at          timestamptz not null default now(),
    constraint uk_heatmap_cell unique (period, grid_level, lat_index, lng_index),
    constraint ck_heatmap_period check (period in ('LAST_1H','LAST_24H','WEEKLY','MONTHLY')),
    constraint ck_heatmap_level check (grid_level between 0 and 3),
    constraint ck_heatmap_counts check (post_count >= 0 and visit_count >= 0 and user_count >= 0),
    constraint ck_heatmap_samples check (cardinality(sample_post_ids) = cardinality(sample_thumbnail_urls)
                                         and cardinality(sample_post_ids) <= 10)
);

create index idx_heatmap_viewport
    on heatmap_cells (period, grid_level, lat, lng);
create index idx_heatmap_density
    on heatmap_cells (period, grid_level, post_count desc, last_posted_at desc);

create table region_stats (
    area_code               integer not null references regions(area_code) on delete cascade,
    period                  varchar(20) not null,
    post_count              integer not null,
    contributor_count       integer not null,
    representative_post_id  bigint references posts(post_id) on delete set null,
    calculated_at           timestamptz not null default now(),
    primary key (area_code, period),
    constraint ck_region_stats_period check (period in ('LAST_1H','LAST_24H','WEEKLY','MONTHLY')),
    constraint ck_region_stats_counts check (post_count >= 0 and contributor_count >= 0)
);

create table heatmap_refresh_state (
    period          varchar(20) not null,
    grid_level      smallint not null,
    calculated_at   timestamptz not null,
    next_refresh_at timestamptz not null,
    primary key (period, grid_level),
    constraint ck_heatmap_refresh_period check (period in ('LAST_1H','LAST_24H','WEEKLY','MONTHLY')),
    constraint ck_heatmap_refresh_level check (grid_level between 0 and 3),
    constraint ck_heatmap_refresh_order check (next_refresh_at > calculated_at)
);

comment on table heatmap_cells is '4단계 격자와 4개 롤링 기간별 지도 집계. 조회 시 재집계하지 않는다 (MAP-008~025)';
comment on column heatmap_cells.sample_thumbnail_urls is 'sample_post_ids와 같은 배열 인덱스의 대표 썸네일 URL (MAP-025)';
comment on column heatmap_cells.visit_count is 'VST 방문 기록 저장 전에는 0. DEC-20260905-007';
