-- SnapHere V13 — USER 도메인 기반
-- 요구사항: USER-001~007, USER-014~023, AUTH-004, AUTH-014
--
-- 기존 인증·게시글 도메인은 users.id(UUID)를 참조한다. 최신 ERD의 사용자
-- 속성은 반영하되, 식별자 타입을 bigint로 바꾸지 않는다 (DEC-20260906-001).

alter table users
    add column bio varchar(200),
    add column terms_agreed_at timestamptz,
    add column upload_blocked_until timestamptz,
    add column push_like_enabled boolean not null default true,
    add column push_follow_enabled boolean not null default true,
    add column push_badge_enabled boolean not null default true,
    add column badge_count integer not null default 0,
    add column follower_count integer not null default 0,
    add column following_count integer not null default 0,
    add column post_count integer not null default 0,
    add column withdrawn_at timestamptz,
    add column purge_scheduled_at timestamptz,
    add column restore_key varchar(64);

alter table users
    add constraint ck_users_bio_length check (bio is null or char_length(bio) <= 200),
    add constraint ck_users_counts_nonnegative
        check (badge_count >= 0 and follower_count >= 0 and following_count >= 0 and post_count >= 0),
    add constraint ck_users_withdrawal_schedule
        check ((status = 'WITHDRAWN' and withdrawn_at is not null and purge_scheduled_at is not null)
            or (status <> 'WITHDRAWN' and withdrawn_at is null and purge_scheduled_at is null));

create index idx_users_purge_scheduled_at
    on users (purge_scheduled_at)
    where status = 'WITHDRAWN';

-- 탈퇴 이력은 유예 종료 후 users 행이 물리 삭제되어도 감사 목적으로 남긴다.
-- 따라서 user_id에는 외래키를 두지 않는다.
create table account_deletion_logs (
    log_id bigint generated by default as identity primary key,
    user_id uuid not null,
    reason varchar(500),
    content_action varchar(30) not null,
    deleted_at timestamptz not null,
    purged_at timestamptz,

    constraint ck_account_deletion_logs_action
        check (content_action in ('KEEP_ANONYMIZED', 'DELETE_ALL')),
    constraint ck_account_deletion_logs_purged_at
        check (purged_at is null or purged_at >= deleted_at)
);

create index idx_account_deletion_logs_user_id
    on account_deletion_logs (user_id, deleted_at desc);
