-- SnapHere V15 — 방문 기록(발자국)
-- 요구사항: VST-001, VST-002, VST-003, VST-004, VST-005, PST-039
-- 설계: 요구사항·기능 명세 v1.1.4 > 6. 데이터 설계 > visits

create table visits (
    visit_id   bigint      generated by default as identity primary key,
    user_id    uuid        not null,
    place_id   bigint      not null,
    post_id    bigint      not null,
    visited_on date        not null,
    created_at timestamptz not null default now(),

    -- 같은 날 같은 장소는 한 번만 기록한다 (VST-002). 애플리케이션에서 조회 후 삽입하면
    -- 같은 사람이 연달아 올릴 때 두 건이 들어가므로 판정을 DB 에 맡긴다.
    constraint uk_visits_daily unique (user_id, place_id, visited_on),
    constraint fk_visits_user  foreign key (user_id)  references users (id) on delete cascade,
    constraint fk_visits_place foreign key (place_id) references places (place_id),
    constraint fk_visits_post  foreign key (post_id)  references posts (post_id)
);

comment on table visits is
'방문 기록. 높음·보통 등급 게시글을 올리면 자동으로 남는다 (VST-001)';
comment on column visits.visited_on is
'방문 일자. Asia/Seoul 기준 날짜다 (SYS-005) — 자정 경계가 사용자가 보는 날짜와 같아야 중복 판정이 납득된다';
comment on column visits.post_id is
'방문의 근거 게시글. 게시글 삭제는 논리 삭제라 행이 남으므로 방문 기록도 함께 남는다 (PST-039).
물리 삭제를 도입할 때는 이 외래키가 막는다 — 방문 사실을 지우려면 먼저 다른 근거로 옮겨야 한다';

-- 내 방문 기록 최신순 커서 페이징 (VST-003). uk_visits_daily 는 (user_id, place_id) 로 시작해
-- 날짜 정렬에 쓸 수 없다.
create index idx_visits_user_recent on visits (user_id, visited_on desc, visit_id desc);

-- 장소 방문자 목록 (VST-005).
create index idx_visits_place on visits (place_id, visited_on desc, visit_id desc);
