-- SnapHere V17 — 수집형 뱃지
-- 요구사항: BDG-001 ~ BDG-014
-- 설계: docs/04-data-design.md > 뱃지 획득 여부에 boolean을 두지 않는 이유 · badges.condition_json

create table badges (
    badge_id       bigint      generated by default as identity primary key,
    code           varchar(100) not null,
    type           varchar(20)  not null,
    name_ko        varchar(100) not null,
    name_en        varchar(100),
    description    varchar(500) not null,
    icon_url       varchar(2048),
    condition_json jsonb        not null,
    event_id       bigint,
    area_code      integer,
    is_obtainable  boolean      not null default true,
    available_from date,
    available_to   date,

    -- BDG-013 은 획득자 수를 보여 준다. 다른 카운터를 전부 비정규화해 두고 여기만 COUNT 를
    -- 돌리면 일관성이 깨진다 (docs/04-data-design.md).
    earned_count   integer      not null default 0,
    created_at     timestamptz  not null default now(),
    updated_at     timestamptz  not null default now(),

    constraint uk_badges_code  unique (code),
    constraint ck_badges_type  check (type in ('EVENT', 'AREA', 'COMPLETION', 'RECORD')),
    constraint ck_badges_dates check (available_to is null or available_from is null
                                      or available_to >= available_from),
    constraint fk_badges_event  foreign key (event_id)  references events (event_id),
    constraint fk_badges_region foreign key (area_code) references regions (area_code)
);

-- 행사 하나에 뱃지는 최대 하나다 (ERD: events 1:0..1 badges). PostgreSQL 의 UNIQUE 는 NULL 을
-- 서로 다르게 보므로 행사 뱃지가 아닌 행들은 이 제약에 걸리지 않는다.
create unique index uk_badges_event on badges (event_id) where event_id is not null;

comment on table badges is
'수집형 뱃지 정의. 획득 조건은 condition_json 이 데이터로 갖는다 (BDG-007)';
comment on column badges.condition_json is
'{"type":"EVENT_PARTICIPATE"} | {"type":"AREA_POST_COUNT","threshold":5}
 | {"type":"VISITED_AREA_COUNT","threshold":17} | {"type":"TOTAL_POST_COUNT","threshold":10}
 평가기는 type 별 분기만 갖고 임계값은 데이터로 읽는다. 행사·지역 뱃지 추가는 데이터 입력으로 끝난다';
comment on column badges.is_obtainable is
'뱃지 자체의 전역 활성 여부. 사용자별 획득 여부와는 다른 축이다 (BDG-010).
 기간이 끝난 행사 뱃지는 진행률 분모에서 빠지지만 이미 받은 사람의 user_badges 행은 남는다';

create table user_badges (
    user_id        uuid        not null,
    badge_id       bigint      not null,
    earned_at      timestamptz not null default now(),
    source_post_id bigint,

    -- 행의 존재가 곧 획득이다. boolean 컬럼을 두면 (전체 사용자 x 전체 뱃지) 조합을 미리
    -- 만들어야 하고, 뱃지를 추가할 때마다 전 사용자에게 행을 뿌려야 한다 (BDG-007 과 충돌).
    constraint pk_user_badges primary key (user_id, badge_id),

    -- BDG-014. 탈퇴하면 뱃지도 함께 사라진다.
    constraint fk_user_badges_user  foreign key (user_id)  references users (id) on delete cascade,
    constraint fk_user_badges_badge foreign key (badge_id) references badges (badge_id) on delete cascade,

    -- 게시글이 물리 삭제돼도 획득 사실은 남는다. CASCADE 면 PST-039 가 깨진다.
    constraint fk_user_badges_post  foreign key (source_post_id) references posts (post_id)
                                    on delete set null
);

comment on table user_badges is
'획득 기록. PK 자체가 중복 지급을 막는다 (BDG-006) — 조회 후 삽입은 동시 요청에서 두 건이 들어간다';

-- 수집함은 badges 를 왼쪽에 두고 user_badges 를 붙인다 (BDG-009, BDG-010).
create index idx_badges_obtainable on badges (type, badge_id) where is_obtainable = true;

-- 방문 지도 하단의 '최근 획득한 뱃지' (VST-010) 와 수집함 정렬.
create index idx_user_badges_recent on user_badges (user_id, earned_at desc);
