-- SnapHere V20 — 통합검색 로그와 PostgreSQL 검색 인덱스
-- 요구사항: SCH-001~SCH-011

create table search_logs (
    log_id      bigint generated by default as identity primary key,
    keyword     varchar(100) not null,
    area_code   integer references regions(area_code),
    searched_at timestamptz not null default now()
);

-- 최근 7일 인기 검색어와 30일 보존기간 정리용.
create index idx_search_logs_searched_at
    on search_logs (searched_at desc);
create index idx_search_logs_area_keyword
    on search_logs (area_code, searched_at desc, keyword);
create index idx_search_keyword
    on search_logs (keyword, searched_at desc);

-- 장소 주소와 게시글 캡션의 앞뒤 와일드카드 검색도 pg_trgm GIN을 탄다.
create index gin_places_addr1_search
    on places using gin ((lower(coalesce(addr1, ''))) gin_trgm_ops)
    where status = 'ACTIVE';
create index gin_posts_content_search
    on posts using gin ((lower(coalesce(content, ''))) gin_trgm_ops)
    where status = 'ACTIVE';

-- 닉네임·태그는 접두어 검색이다. text_pattern_ops로 LIKE 'prefix%'를 받는다.
create index idx_users_nickname_search
    on users ((lower(nickname)) text_pattern_ops, follower_count desc, post_count desc, id)
    where status = 'ACTIVE' and nickname is not null;
create index idx_tags_normalized_search
    on tags (normalized_name text_pattern_ops, usage_count desc, tag_id);
