-- SnapHere V2 — 장소 기준정보와 장소
-- 요구사항: PLC-001, PLC-002, PLC-003, PLC-007, PLC-020, PLC-022, PLC-023
-- 설계: docs/12-db-schema.dbml · docs/04-data-design.md
--
-- PostGIS 확장이 필요하다. 관리형 DB(RDS 등)에서는 확장 생성 권한이 있는 계정으로 한 번
-- 실행해 두고 애플리케이션 계정에는 권한을 주지 않아도 된다.

create extension if not exists postgis;
create extension if not exists pg_trgm;

-- ─────────────────────────────────────────── regions · 17개 시도 마스터 (PLC-001)
create table regions (
    area_code                     integer       primary key,
    name_ko                       varchar(50)   not null,
    name_en                       varchar(100),
    representative_image_url      varchar(2048),
    default_event_verify_radius_m integer,
    created_at                    timestamptz   not null default now(),
    updated_at                    timestamptz   not null default now(),
    constraint ck_regions_event_radius check (default_event_verify_radius_m is null
                                              or default_event_verify_radius_m > 0)
);

comment on table  regions is '시도 마스터. 시도 코드는 비연속(1~8, 31~39)';
comment on column regions.default_event_verify_radius_m is '행사 인증 반경 지역 기본값. null 이면 2,000m (PLC-022)';

-- ─────────────────────────────────────────── sigungu · 시군구 마스터 (PLC-002, PLC-020)
create table sigungu (
    area_code    integer     not null,
    sigungu_code integer     not null,
    name_ko      varchar(50) not null,
    name_en      varchar(100),
    primary key (area_code, sigungu_code),
    constraint fk_sigungu_region foreign key (area_code) references regions (area_code)
);

-- ─────────────────────────────────────────── places · 관광지 + 사용자 장소 (PLC-003)
create table places (
    place_id        bigint        generated by default as identity primary key,
    place_type      varchar(20)   not null,
    content_id      bigint,
    content_type_id integer,
    title           varchar(200)  not null,
    addr1           varchar(500),
    lat             double precision,
    lng             double precision,
    verify_radius_m integer       not null,
    area_code       integer       not null,
    sigungu_code    integer,
    status          varchar(20)   not null default 'ACTIVE',
    post_count      integer       not null default 0,
    visit_count     integer       not null default 0,
    view_count      integer       not null default 0,
    created_by      uuid,
    created_at      timestamptz   not null default now(),
    updated_at      timestamptz   not null default now(),

    -- 좌표는 lat·lng 를 원본으로 두고 아래 두 열을 파생시킨다.
    -- 애플리케이션이 따로 채우면 어긋날 수 있어 DB 가 계산하게 맡긴다.
    has_coordinate  boolean generated always as (lat is not null and lng is not null) stored,
    geom            geography(Point, 4326) generated always as (
                        case
                            when lat is null or lng is null then null
                            else st_setsrid(st_makepoint(lng, lat), 4326)::geography
                        end
                    ) stored,

    constraint ck_places_type   check (place_type in ('OFFICIAL', 'USER')),
    constraint ck_places_status check (status in ('ACTIVE', 'HIDDEN', 'DELETED')),
    constraint ck_places_radius check (verify_radius_m > 0),
    constraint ck_places_lat    check (lat is null or (lat between -90 and 90)),
    constraint ck_places_lng    check (lng is null or (lng between -180 and 180)),
    constraint uk_places_content unique (content_id, content_type_id),
    constraint fk_places_region  foreign key (area_code) references regions (area_code),
    constraint fk_places_sigungu foreign key (area_code, sigungu_code)
                                 references sigungu (area_code, sigungu_code),
    constraint fk_places_creator foreign key (created_by) references users (id)
);

comment on table  places is '관광지와 사용자 장소를 한 테이블에 둔다. 지도·주변탐색이 둘을 함께 그리므로 나누면 모든 조회가 UNION 이 된다';
comment on column places.lat is 'TourAPI mapy';
comment on column places.lng is 'TourAPI mapx';
comment on column places.geom is '생성 열. ST_DWithin(geom, :point, :radius_m) 의 반경은 미터 단위다';
comment on column places.has_coordinate is '생성 열. false 면 주변탐색·히트맵·등급 판정에서 제외한다 (PLC-007)';
comment on column places.verify_radius_m is '관광지 500m · 사용자 장소 100m 기본. 관리자가 개별 조정할 수 있다 (PST-027, PLC-022)';

-- 주변 탐색·지도 마커 (MAP-026, MAP-030)
create index gix_places_geom on places using gist (geom);
-- 장소명 한글 부분어 검색. LIKE '%경복%' 도 인덱스를 탄다 (SCH-004)
create index gin_places_title on places using gin (title gin_trgm_ops);
-- 지역·타입별 장소 목록 (PLC-011)
create index idx_places_area_type on places (area_code, place_type) where status = 'ACTIVE';
