-- SnapHere V3 — 게시글·사진·해시태그·등급 감사 로그
-- 요구사항: PST-001~PST-004, PST-016~PST-021, PST-028~PST-031, CMU-025~CMU-032
-- 설계: docs/12-db-schema.dbml · docs/04-data-design.md
--
-- users.id 가 uuid 이므로 posts.user_id 도 uuid 다 (V1__auth_schema.sql).

-- ─────────────────────────────────────────── posts (PST-016)
create table posts (
    post_id                bigint        generated by default as identity primary key,
    user_id                uuid          not null,
    place_id               bigint        not null,
    event_id               bigint,
    area_code              integer       not null,
    content                varchar(5000),
    original_language_code varchar(10),
    tier                   varchar(10)   not null,
    lat                    double precision,
    lng                    double precision,
    taken_at               timestamptz,
    source                 varchar(20),
    like_count             integer       not null default 0,
    comment_count          integer       not null default 0,
    view_count             integer       not null default 0,
    status                 varchar(20)   not null default 'ACTIVE',
    created_at             timestamptz   not null default now(),
    updated_at             timestamptz   not null default now(),
    deleted_at             timestamptz,

    constraint ck_posts_tier    check (tier in ('HIGH', 'MEDIUM', 'LOW')),
    constraint ck_posts_source  check (source is null or source in ('CAMERA', 'ALBUM')),
    constraint ck_posts_status  check (status in ('ACTIVE', 'HIDDEN', 'DELETED')),
    constraint ck_posts_counts  check (like_count >= 0 and comment_count >= 0 and view_count >= 0),
    constraint fk_posts_user    foreign key (user_id)   references users (id),
    constraint fk_posts_place   foreign key (place_id)  references places (place_id),
    constraint fk_posts_region  foreign key (area_code) references regions (area_code)
);

comment on column posts.place_id  is '장소 없이는 게시할 수 없다 (PST-002)';
comment on column posts.event_id  is '진행 중 행사 연결. events 테이블이 생기면 그때 외래키를 건다 (EVT-018)';
comment on column posts.area_code is '클라이언트 값을 믿지 않고 장소에서 역산한다 (PST-018)';
comment on column posts.tier      is '서버가 판정한다. 클라이언트가 보낸 값은 무시한다 (PST-022)';
comment on column posts.lat       is '촬영 좌표. 공개 이미지에서는 EXIF 를 지우지만 판정 근거로 여기 남긴다 (PST-020)';
comment on column posts.source    is '판정 입력값이라 null 을 허용한다. null 이면 등급 상향 근거가 없다';

-- 카운터는 비정규화한다. 목록 응답마다 COUNT 를 돌리면 무한 스크롤이 못 버틴다.
-- 논리 삭제라 모든 조회에 status = 'ACTIVE' 가 붙으므로 부분 인덱스로 받는다.
create index idx_posts_area_created on posts (area_code, created_at desc) where status = 'ACTIVE';
create index idx_posts_place        on posts (place_id, created_at desc)  where status = 'ACTIVE';
create index idx_posts_user         on posts (user_id, created_at desc)   where status = 'ACTIVE';

-- ─────────────────────────────────────────── post_images (PST-001, PST-021, PST-031)
create table post_images (
    post_image_id bigint        generated by default as identity primary key,
    post_id       bigint        not null,
    image_key     varchar(1024) not null,
    thumbnail_url varchar(2048),
    aspect_ratio  numeric(6, 4),
    sort_order    smallint      not null,
    image_hash    varchar(64),
    created_at    timestamptz   not null default now(),

    constraint ck_post_images_order  check (sort_order between 1 and 4),
    constraint ck_post_images_ratio  check (aspect_ratio is null or aspect_ratio > 0),
    constraint uk_post_images_order  unique (post_id, sort_order),
    constraint uk_post_images_hash   unique (post_id, image_hash),
    constraint fk_post_images_post   foreign key (post_id) references posts (post_id) on delete cascade
);

comment on table  post_images is '게시글당 1~4장 (PST-001)';
comment on column post_images.image_key    is 'S3 오브젝트 키. 공개 URL 은 이 키로 조립한다';
comment on column post_images.aspect_ratio is '메이슨리 카드 높이를 이미지 도착 전에 잡아야 한다 (PST-021)';
comment on column post_images.thumbnail_url is '후처리 배치가 채운다 (PST-019, JOB-003)';
comment on column post_images.image_hash   is '본인 계정 안 중복 업로드 차단 (PST-031)';

-- ─────────────────────────────────────────── tags · post_tags (PST-004, CMU-025~032)
create table tags (
    tag_id          bigint      generated by default as identity primary key,
    name            varchar(50) not null,
    normalized_name varchar(50) not null,
    theme_code      varchar(30),
    usage_count     bigint      not null default 0,
    created_at      timestamptz not null default now(),

    constraint uk_tags_normalized_name unique (normalized_name),
    constraint ck_tags_usage           check (usage_count >= 0)
);

comment on column tags.normalized_name is '소문자 변환 + 공백 제거 (CMU-025)';
comment on column tags.theme_code      is 'K-컬처 테마 랭킹 키 (RNK-005)';

create table post_tags (
    post_id      bigint      not null,
    tag_id       bigint      not null,
    is_locked    boolean     not null default false,
    is_suggested boolean     not null default false,
    created_at   timestamptz not null default now(),

    primary key (post_id, tag_id),
    constraint fk_post_tags_post foreign key (post_id) references posts (post_id) on delete cascade,
    constraint fk_post_tags_tag  foreign key (tag_id)  references tags (tag_id)
);

comment on table  post_tags is '게시글 수정 시 이 연결을 전부 지우고 다시 넣는다. 차이 계산은 버그를 부른다 (CMU-032)';
comment on column post_tags.is_locked    is '행사 고정 태그. 사용자가 뗄 수 없다 (EVT-018)';
comment on column post_tags.is_suggested is '추천을 채택한 태그. 추천 로직 개선 지표 (CMU-029)';

-- 태그로 게시글 검색 (CMU-030). PK 는 post_id 부터라 이 방향을 못 탄다.
create index idx_post_tags_tag on post_tags (tag_id);

-- ─────────────────────────────────────────── tier_logs (PST-028, PST-047, PST-049)
create table tier_logs (
    tier_log_id            bigint      generated by default as identity primary key,
    post_id                bigint      not null,
    tier                   varchar(10) not null,
    source                 varchar(20),
    taken_at               timestamptz,
    has_taken_coordinate   boolean     not null,
    distance_m             integer,
    applied_radius_m       integer     not null,
    threshold_high_minutes integer     not null,
    threshold_medium_days  integer     not null,
    decided_reason         varchar(50) not null,
    decided_at             timestamptz not null,

    constraint ck_tier_logs_tier   check (tier in ('HIGH', 'MEDIUM', 'LOW')),
    constraint ck_tier_logs_source check (source is null or source in ('CAMERA', 'ALBUM')),
    constraint fk_tier_logs_post   foreign key (post_id) references posts (post_id) on delete cascade
);

comment on table tier_logs is
'판정 근거 감사 로그. posts 에 합치지 않는다 — 기준(반경·10분·30일)이 바뀌어도 과거 판정을 재현할 수 있어야 하므로 입력값을 스냅샷으로 남긴다. 현재 등급은 posts.tier, 판정 이유는 이 테이블의 최신 1행';
comment on column tier_logs.distance_m is '촬영 좌표가 없으면 null. 그 자체가 낮음 판정 근거다 (PST-025)';

create index idx_tier_logs_post on tier_logs (post_id, decided_at desc);
