-- SnapHere V9 — 신고
-- 요구사항: PST-043, PST-044, PST-045, SYS-017
-- 설계: docs/05-erd-reference.md > reports
--
-- 대상이 게시글·장소·댓글·사용자로 늘어날 수 있어 target_id 에 외래키를 걸 수 없다.
-- 지금 열어 두는 것은 POST 와 PLACE 뿐이다 — 요구사항 근거가 있는 범위다 (PST-043, PLC-023).

create table reports (
    report_id   bigint         generated by default as identity primary key,
    reporter_id uuid           not null,
    target_type varchar(20)    not null,
    target_id   bigint         not null,
    reason      varchar(30)    not null,
    detail      varchar(1000),
    status      varchar(20)    not null default 'PENDING',
    action      varchar(20),
    reviewed_at timestamptz,
    created_at  timestamptz    not null default now(),

    constraint ck_reports_target_type check (target_type in ('POST', 'PLACE')),
    constraint ck_reports_reason check (reason in
        ('INAPPROPRIATE', 'COPYRIGHT', 'PLACE_MISMATCH', 'SPAM', 'OTHER')),
    constraint ck_reports_status check (status in ('PENDING', 'REVIEWED')),
    constraint ck_reports_action check (action is null or action in ('KEEP', 'HIDE', 'DELETE')),
    constraint ck_reports_reviewed check ((status = 'PENDING' and reviewed_at is null)
                                       or (status = 'REVIEWED' and reviewed_at is not null)),
    constraint uk_reports_reporter unique (reporter_id, target_type, target_id),
    constraint fk_reports_reporter foreign key (reporter_id) references users (id) on delete cascade
);

comment on table reports is
'신고. (reporter_id, target_type, target_id) UNIQUE 로 같은 사람이 같은 대상을 두 번 신고하지 못하게 한다 — 애플리케이션에서 조회 후 삽입하면 연달아 누를 때 두 건이 들어간다 (PST-044)';
comment on column reports.action is
'운영자 검토 결과. KEEP 복구 · HIDE 가림 · DELETE 삭제 (SYS-017). 검토 전에는 null 이다';
comment on column reports.reviewed_at is
'검토 시각. status 와 짝이 맞아야 하므로 CHECK 로 묶었다 — 검토했다면서 시각이 없거나 그 반대인 행을 막는다';

-- 누적 건수 판정(PST-045)과 운영자 대기 목록(SYS-017)에 쓴다.
create index idx_reports_target on reports (target_type, target_id);
create index idx_reports_pending on reports (created_at) where status = 'PENDING';
