package com.snaphere.api.social;
import com.snaphere.api.auth.*; import com.snaphere.api.common.error.*; import com.snaphere.api.common.web.*; import jakarta.persistence.EntityManager; import org.springframework.data.domain.PageRequest; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class FollowService { private final FollowRepository follows; private final UserRepository users; private final PagingProperties paging; private final EntityManager em; public FollowService(FollowRepository f,UserRepository u,PagingProperties p,EntityManager e){follows=f;users=u;paging=p;em=e;}
 @Transactional public SocialDtos.FollowResult follow(UUID actor,UUID target){if(actor.equals(target))throw new ApiException(ErrorCode.SOC_SELF_FOLLOW);User source=users.findLockedById(actor).orElseThrow(()->new ApiException(ErrorCode.AUTH_REQUIRED));if(source.getStatus()!=UserStatus.ACTIVE)throw new ApiException(ErrorCode.AUTH_REQUIRED);User t=active(target);if(follows.existsById(new FollowId(actor,target)))return new SocialDtos.FollowResult(target,true,t.getFollowerCount());Instant today=LocalDate.now(ZoneId.of("Asia/Seoul")).atStartOfDay(ZoneId.of("Asia/Seoul")).toInstant();if(follows.countByIdFollowerIdAndCreatedAtGreaterThanEqual(actor,today)>=200)throw new ApiException(ErrorCode.SOC_DAILY_LIMIT);if(follows.insertIfAbsent(actor,target)==1){users.addFollowingCount(actor,1);users.addFollowerCount(target,1);em.flush();em.refresh(t);}return new SocialDtos.FollowResult(target,true,t.getFollowerCount());}
 @Transactional public SocialDtos.FollowResult unfollow(UUID actor,UUID target){User source=users.findLockedById(actor).orElseThrow(()->new ApiException(ErrorCode.AUTH_REQUIRED));if(source.getStatus()!=UserStatus.ACTIVE)throw new ApiException(ErrorCode.AUTH_REQUIRED);User t=active(target);if(follows.deleteRelation(actor,target)==1){users.addFollowingCount(actor,-1);users.addFollowerCount(target,-1);em.flush();em.refresh(t);}return new SocialDtos.FollowResult(target,false,t.getFollowerCount());}
 @Transactional(readOnly=true) public CursorPage<SocialDtos.UserSummary> followers(UUID target,String cursor,Integer size,Optional<UUID> viewer){requireUser(target);return page(follows.followers(target,at(cursor),id(cursor),PageRequest.of(0,paging.resolve(size)+1)),true,size,viewer);}
 @Transactional(readOnly=true) public CursorPage<SocialDtos.UserSummary> following(UUID target,String cursor,Integer size,Optional<UUID> viewer){requireUser(target);return page(follows.following(target,at(cursor),id(cursor),PageRequest.of(0,paging.resolve(size)+1)),false,size,viewer);}
 @Transactional(readOnly=true) public List<SocialDtos.UserSummary> recommendations(UUID viewer,Integer limit){int size=limit==null?10:Math.min(Math.max(limit,1),30);List<User> rows=users.recommendations(viewer,PageRequest.of(0,size));return summaries(rows,Optional.of(viewer));}
 private CursorPage<SocialDtos.UserSummary> page(List<Follow> rows,boolean followersList,Integer requested,Optional<UUID> viewer){int limit=paging.resolve(requested);boolean next=rows.size()>limit;if(next)rows=rows.subList(0,limit);List<UUID> ids=rows.stream().map(f->followersList?f.getId().getFollowerId():f.getId().getFollowingId()).toList();List<User> byId=users.findAllById(ids);Map<UUID,User> map=new HashMap<>();byId.forEach(u->map.put(u.getId(),u));List<User> ordered=ids.stream().map(map::get).filter(Objects::nonNull).toList();String n=next?new FollowCursor(rows.get(rows.size()-1).getCreatedAt(),ids.get(ids.size()-1)).encode():null;return CursorPage.of(summaries(ordered,viewer),n);}
 private List<SocialDtos.UserSummary> summaries(List<User> rows,Optional<UUID> viewer){Set<UUID> ids=new HashSet<>();rows.forEach(u->ids.add(u.getId()));Set<UUID> following=viewer.map(v->follows.followed(v,ids)).orElse(Set.of());Set<UUID> followedBy=viewer.map(v->follows.followedBy(v,ids)).orElse(Set.of());return rows.stream().map(u->new SocialDtos.UserSummary(u.getId(),u.getNickname(),u.getProfileImageUrl(),u.getBio(),viewer.isPresent()?following.contains(u.getId()):null,viewer.isPresent()?followedBy.contains(u.getId()):null)).toList();}
 private void requireUser(UUID id){active(id);} private User active(UUID id){User u=users.findById(id).orElseThrow(()->new ApiException(ErrorCode.USER_NOT_FOUND));if(u.getStatus()!=UserStatus.ACTIVE)throw new ApiException(ErrorCode.USER_NOT_FOUND);return u;} private FollowCursor c(String x){return FollowCursor.decode(x);} private Instant at(String x){FollowCursor c=c(x);return c==null?null:c.createdAt();} private UUID id(String x){FollowCursor c=c(x);return c==null?null:c.userId();}
}
