package com.snaphere.api.auth;
import com.snaphere.api.common.error.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
@Service class AuthService { private static final Duration REFRESH_TTL=Duration.ofDays(30); private final UserRepository users;private final UserDeviceRepository devices;private final RefreshTokenRepository refreshTokens;private final GoogleTokenVerifier google;private final JwtService jwt;private final AuthProperties properties;
 AuthService(UserRepository u,UserDeviceRepository d,RefreshTokenRepository r,GoogleTokenVerifier g,JwtService j,AuthProperties p){users=u;devices=d;refreshTokens=r;google=g;jwt=j;properties=p;}
 @Transactional AuthDtos.AuthResult googleLogin(AuthDtos.GoogleLoginRequest request){GoogleIdentity identity=google.verify(request.idToken());User user=users.findByGoogleSubject(identity.subject()).orElseGet(()->users.save(User.newGoogleUser(identity.subject(),identity.email(),identity.picture())));if(user.getStatus()==UserStatus.WITHDRAWN){if(user.getPurgeScheduledAt()==null||!user.getPurgeScheduledAt().isAfter(Instant.now()))throw new ApiException(ErrorCode.USER_RECOVERY_EXPIRED);return new AuthDtos.AuthResult(null,null,false,true,user.getRestoreKey());}UserDevice device=upsertDevice(user,request.deviceId(),request.platform(),request.fcmToken(),null);return new AuthDtos.AuthResult(issue(user,device),view(user),!user.isOnboardingCompleted(),false,null);}
 @Transactional AuthDtos.AuthResult restore(AuthDtos.RestoreAccountRequest request){if(!Boolean.TRUE.equals(request.confirmDataLoss()))throw new ApiException(ErrorCode.COMMON_400,Map.of("field","confirmDataLoss"));User user=users.findByRestoreKey(request.restoreKey()).orElseThrow(()->new ApiException(ErrorCode.USER_RESTORE_KEY_INVALID));if(user.getStatus()!=UserStatus.WITHDRAWN||user.getPurgeScheduledAt()==null||!user.getPurgeScheduledAt().isAfter(Instant.now()))throw new ApiException(ErrorCode.USER_RECOVERY_EXPIRED);UserDevice device=devices.findFirstByUserIdOrderByUpdatedAtDesc(user.getId()).orElseThrow(()->new ApiException(ErrorCode.USER_RESTORE_KEY_INVALID));user.restore(request.nickname().trim());return new AuthDtos.AuthResult(issue(user,device),view(user),false,false,null);}
 @Transactional AuthDtos.UserView onboard(AuthPrincipal principal,AuthDtos.OnboardingRequest request){if(!properties.termsVersion().equals(request.termsVersion()))throw new ApiException(ErrorCode.AUTH_TERMS_REQUIRED);if(request.nickname().isBlank())throw new ApiException(ErrorCode.USER_NICKNAME_INVALID);User user=users.findById(principal.userId()).orElseThrow(()->new ApiException(ErrorCode.AUTH_REQUIRED));user.completeOnboarding(request.nickname().trim(),request.termsVersion(),request.locale());return view(user);}
 @Transactional AuthDtos.TokenBundle refresh(AuthDtos.RefreshRequest request){RefreshToken current=refreshTokens.findByTokenHash(hash(request.refreshToken())).orElseThrow(()->new ApiException(ErrorCode.AUTH_INVALID_REFRESH));if(!current.getDevice().getDeviceIdentifier().equals(request.deviceId()))throw new ApiException(ErrorCode.AUTH_INVALID_REFRESH);if(current.isRevoked()){revokeAll(current.getUser());throw new ApiException(ErrorCode.AUTH_TOKEN_REUSED);}if(current.getExpiresAt().isBefore(Instant.now()))throw new ApiException(ErrorCode.AUTH_REFRESH_EXPIRED);current.revoke();return issue(current.getUser(),current.getDevice());}
 @Transactional void logout(AuthPrincipal p){UserDevice d=devices.findById(p.deviceId()).filter(device->device.getUser().getId().equals(p.userId())).orElseThrow(()->new ApiException(ErrorCode.AUTH_REQUIRED));d.clearFcmToken();refreshTokens.findAllByDeviceId(d.getId()).forEach(RefreshToken::revoke);} @Transactional void logoutAll(AuthPrincipal p){User u=users.findById(p.userId()).orElseThrow(()->new ApiException(ErrorCode.AUTH_REQUIRED));revokeAll(u);}
 private void revokeAll(User u){refreshTokens.findAllByUserId(u.getId()).forEach(RefreshToken::revoke);} private UserDevice upsertDevice(User u,String id,Platform p,String fcm,String version){UserDevice d=devices.findByUserIdAndDeviceIdentifier(u.getId(),id).orElseGet(()->devices.save(UserDevice.create(u,id,p,fcm,version)));d.update(p,fcm,version);return d;} private AuthDtos.TokenBundle issue(User u,UserDevice d){String raw="rt_"+UUID.randomUUID()+UUID.randomUUID();refreshTokens.save(RefreshToken.issue(u,d,hash(raw),Instant.now().plus(REFRESH_TTL)));return new AuthDtos.TokenBundle(jwt.issue(u,d),7200,raw,REFRESH_TTL.toSeconds());} private String hash(String raw){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}} private AuthDtos.UserView view(User u){return new AuthDtos.UserView(u.getId().toString(),u.getEmail(),u.getNickname(),u.getProfileImageUrl(),u.getStatus().name(),u.getRole().name(),u.getLocale());}}
