package com.snaphere.api.auth;
import com.snaphere.api.common.web.*; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("${snaphere.api.base-path:/api/v1}/auth") class AuthController { private final AuthService service; AuthController(AuthService s){service=s;}
 @PostMapping("/google") ResponseEntity<ApiResponse<AuthDtos.AuthResult>> google(@Valid @RequestBody AuthDtos.GoogleLoginRequest body,HttpServletRequest request){return ResponseEntity.ok(ApiResponse.ok(service.googleLogin(body),TraceIdFilter.currentTraceId(request)));}
 @PostMapping("/onboarding") ResponseEntity<ApiResponse<AuthDtos.UserView>> onboarding(@AuthenticationPrincipal AuthPrincipal principal,@Valid @RequestBody AuthDtos.OnboardingRequest body,HttpServletRequest request){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.ok(service.onboard(principal,body),TraceIdFilter.currentTraceId(request)));}
 @PostMapping("/refresh") ResponseEntity<ApiResponse<AuthDtos.TokenBundle>> refresh(@Valid @RequestBody AuthDtos.RefreshRequest body,HttpServletRequest request){return ResponseEntity.ok(ApiResponse.ok(service.refresh(body),TraceIdFilter.currentTraceId(request)));}
 @PostMapping("/restore") ResponseEntity<ApiResponse<AuthDtos.AuthResult>> restore(@Valid @RequestBody AuthDtos.RestoreAccountRequest body,HttpServletRequest request){return ResponseEntity.ok(ApiResponse.ok(service.restore(body),TraceIdFilter.currentTraceId(request)));}
 @PostMapping("/logout") ResponseEntity<Void> logout(@AuthenticationPrincipal AuthPrincipal principal){service.logout(principal);return ResponseEntity.noContent().build();} @PostMapping("/logout-all") ResponseEntity<Void> logoutAll(@AuthenticationPrincipal AuthPrincipal principal){service.logoutAll(principal);return ResponseEntity.noContent().build();}
}
